### ISSUE TITLE
release new version for php8?

### ISSUE THREAD

**Issue by iamgold** [AlaaSarhan/php-flatten#21]
Hi,
    We are happy to see the master branch changing config of composer for compatible with PHP8. 
     Is going to release the new version with this changed recently?
     
     We are very appreciate and need your help.
     thanks.

**Comment by AlaaSarhan** [comment]
@iamgold  released https://github.com/AlaaSarhan/php-flatten/releases/tag/v4.0.0

**Comment by iamgold** [comment]
@AlaaSarhan Thanks a log
